namespace: "microsoft"
name: "sql"
version: "1.0.10"
description: "An Ansible role for Microsoft SQL Server management"

authors:
  - "Sergei Petrosian <spetrosi@redhat.com>"

repository: "https://github.com/linux-system-roles/mssql"
documentation: "https://github.com/linux-system-roles/mssql/blob/master/README.md"
issues: "https://github.com/linux-system-roles/mssql/issues"

readme: "README.md"

license:
    - MIT

dependencies: {}

tags:
  - "mssql"
  - "microsoft"
  - "sql"
  - "database"

build_ignore:
  - tests/server/artifacts
