# SPDX-License-Identifier: MIT
---
__mssql_server_repository: >-
  https://packages.microsoft.com/rhel/7/mssql-server-2019/
__mssql_client_repository: >-
  https://packages.microsoft.com/rhel/7/prod/
